site_name: "BESAFE - Documentation"
site_description: "Wiki technique du projet BESAFE"
site_url: "https://ilangaussin.github.io/BESAFE/"

docs_dir: docs

theme:
  name: material
  language: fr
  palette:
    scheme: slate
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight

plugins:
  - search

nav:
  - Accueil: index.md

  - Architecture:
      - Vue d'ensemble: architecture/architecture.md
      - Inventaire matériel: architecture/inventaire-materiel.md
      - VLAN / Plan IP: architecture/vlan-plan-ip.md
      - Schéma: architecture/schema.md

  - Réseaux:
      - Switch: reseaux/switch.md
      - Stormshield: reseaux/stormshield.md

  - Sécurité:
      - Wazuh: security/wazuh.md

  - Services:
      - Vaultwarden: services/vaultwarden.md
      - Nextcloud: services/nextcloud.md
      - GLPI: services/glpi.md
      - Nginx Proxy Manager: services/nginx-proxy-manager.md

  - Supervision:
      - Centreon: supervision/centreon.md
      - Grafana: supervision/grafana.md
      - Zabbix: supervision/zabbix.md

  - Systèmes:
      - AD DS / DHCP / DNS: systemes/ad-ds-dhcp-dns.md
      - PKI / AD CS: systemes/pki-adcs.md
      - iSCSI: systemes/iscsi.md

  - Virtualisation:
      - ESXi: virtualisation/esxi.md
      - vCenter: virtualisation/vcenter.md
